### ISSUE TITLE
CORS policy

### ISSUE THREAD

**Issue by harpiyacloud** [RobertoPrevato/BlackSheep#28]
Hi,

 How can we use the CORS policy in the system. Will you make an addition for this? If you don't have an add-on plan for now, can we do it with middleware support?

**Comment by RobertoPrevato** [comment]
Hi @harpiyacloud,
Yes, I am planning to add support for CORS configuration through an high level API. This is the next thing in line that I want to implement.

It is already possible to do it with a middleware (or with an async function wrapper). This is a simplified starting point of how I plan to implement this feature: 

```python
from typing import Callable, Awaitable, List, Optional
from blacksheep import Request, Response


class CORSOptions:

    def __init__(self,
                 allowed_origins: List[str],
                 allowed_methods: List[str],
                 allowed_headers: List[str],
                 access_control_max_age: int = 600
                 ):
        self.access_control_max_age = access_control_max_age
        self.allowed_origins = allowed_origins
        self.allowed_methods = allowed_methods
        self.allowed_headers = allowed_headers

    @classmethod
    def default(cls):
        return cls(["*"], ["GET", "POST"], [...], 600)

class CORSMiddleware:

    def __init__(self, options: Optional[CORSOptions] = None):
        if options is None:
            options = CORSOptions.default()
        self._options = options

    @property
    def options(self) -> CORSOptions:
        return self._options

    async def __call__(self,
                       request: Request,
                       handler: Callable[[Request], Awaitable[Response]]
                       ) -> Response:
        # TODO: check method, if Options request
        # check origins, headers
        # ref. https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
        response = await handler(request)
        # TODO: add headers as appropriate
        return response
```

Such callable class can then be added to the list of application middlewares:
```
app.middlewares.append(CORSMiddleware())
```

I am planning to support various configurations depending on the endpoints (like various policies applicable to various endpoints, each policy with its own options).

Lately I had little spare time to work on my web framework, otherwise this would be already in place.

**Comment by harpiyacloud** [comment]
Hi,

Thank you very much for your reply. I hope your system will be better and better. I had a few more questions. I want to use pony orm. I tried to connect with the event (on_start, on_stop) in the template you created, but I was not successful. Can you share a sample code? and finally how can I use the jwt system for guarpost. I'm sorry if I asked too many questions.

**Comment by harpiyacloud** [comment]
Hello again,

I was able to solve the problem of connecting to the database.  :)

**Comment by RobertoPrevato** [comment]
Hi,
Sorry for replying so late. You didn't ask too many questions, I didn't answer just because I wanted to read a bit about Pony ORM and lately I have little time. :)

I am glad you resolved the issue connecting to the database.

It looks like Pony ORM has a synchronous API. If you are building a web application that will be used by many users concurrently, you should consider using it through a thread pool executor, with asyncio. Otherwise you block the event loop and this could be a problem.

There is an example here (I didn't test it), it could be useful: https://gist.github.com/grudko/4c1dcd2a2eb29bc3d98cd19bfd916cbd

---
About guardpost and JWT support, my `guardpost-jwt` package is not complete. However, this could be a good opportunity for me to complete it, and I can help implementing the class to validate JWT tokens.

I wrote a [detailed blog post about validating JWT with Python](https://robertoprevato.github.io/Validating-JWT-Bearer-tokens-from-Azure-AD-in-Python/).

**Comment by harpiyacloud** [comment]
Hi @RobertoPrevato 

Thank you so much for your information. In the future, I will try to share information about my work.I follow your success with pleasure.
