### ISSUE TITLE
Change to wiki text.

### ISSUE THREAD

**Issue by tomchristie** [RobertoPrevato/BlackSheep#7]
Something worth changing on the wiki text:

"Christie is recommending Python community to adopt a standard API he designed, ASGI"

The ASGI spec is authored and maintained by Andrew Godwin. I'm just a supporter of its adoption. 😄

**Comment by tomchristie** [comment]
Obvs. I think you'd have more impact if your work was more tightly targeted as being towards a Cythonised ASGI server (or HTTP protocol to plug into uvicorn), since you'd then be able to use that with Responder, Quart, Bocadillo, FastAPI, and Starlette.

That way we're all pushing forwards together. Rather than having a Cythonised component that's tightly coupled to one particular framework, ala Vibora.

But, fair enough if it's really not something you're interested in pursuing.

**Comment by RobertoPrevato** [comment]
Hi @tomchristie,
Thank You for your feedback! I updated the wiki to correct my error. :)
I avoided ASGI because I wanted to experiment with a framework that uses custom classes to handle headers, cookies, etc. I am influenced by ASP.NET framework from .NET community, since at work I always worked with .NET technology. 

I know this means sacrificing interoperability with other libraries and also user-friendliness, since enforcing specific classes is not user-friendly. The good side is that the framework should use less resources. If the tests I made locally with `wrk` are correct, the approach pays off under this point of view. 

However, I will look more into ASGI and see what it would take to adopt it, while still using custom classes for http objects. A few months ago I tried to write a Cython protocol for `uvicorn`, but it's hard to optimize in Cython, when working with dictionaries. Do you think there is a way to use ASGI with [extension types](https://cython.readthedocs.io/en/latest/src/tutorial/cdef_classes.html)?

PS.
I'm honored that you dedicated some of your time to read and comment my work.

**Comment by tomchristie** [comment]
> it's hard to optimize in Cython, when working with dictionaries.

You could consider working with strict types throughout the codebase, and either:

* Only jump to instantiating a dict for the final call into the ASGI app.
* Implement a mapping interface onto the type, so that it *is* dictionary-like.

Given that the end-developer will be working with Python at the application level anyways, a dict interface vs. objects isn't going to be a measurable effect under any sensible real-world conditions. (Tho it could skew in some limited micro-benchmarking.)

**Comment by RobertoPrevato** [comment]
Thanks for the heads up, when I have time, I look into both options. 

I only partially agree with this sentence:
> Given that the end-developer will be working with Python at the application level anyways, a dict interface vs. objects isn't going to be a measurable effect under any sensible real-world conditions.

It is true: most real applications will be slower anyway. This happens also in .NET community, even though C# is statically compiled and faster than Python. People use ASP.NET Core which is really fast ([ref](https://www.ageofascent.com/2019/02/04/asp-net-core-saturating-10gbe-at-7-million-requests-per-second/)), but then in practice every application is over-engineered, with lots of design patterns and abstraction layers ([Automapper](https://github.com/AutoMapper/AutoMapper), [Mediator](https://github.com/jbogard/MediatR) &ast;&ast;**sigh**&ast;&ast;, dependency injection for everything, etc.) - so at the end a real application can answer just 300 requests a second, for a simple `is alive` endpoint, deployed for example on a Standard S2 machine in Azure (~70 EUR / mo).

But the building blocks should be fast and efficient, in my opinion. For example, I don't like the comments from `aiohttp` contributors I read in GitHub, I think they are in denial that aiohttp could be improved. They blame bad performance on Python language and say: _"Real applications will be slow anyway, if you need something fast use another programming language"_. Then, the source code of this framework is full of if statements to handle many corner cases, and is not following SOLID. Its performance could be improved, if only those code execution fees were removed, through refactoring. I am saying this respectfully and while I wrote several articles promoting the use of aiohttp.

I found [David Fowler](https://twitter.com/davidfowl) exaggerated when he blasted all .NET programmers who declare strings before using them once, saying it's inefficient performance-wise, but I think it makes sense in his position, since he's working on ASP.NET Core. :)

**Comment by tomchristie** [comment]
> But the building blocks should be fast and efficient

Well indeed - completely agreed there.

I'm just advocating for fast and efficient building blocks, rather than fast and efficient tightly coupled full-frameworks.

Anyways, I'd best crack on with other stuff. Good work on Black Sheep. 👍 😃

**Comment by RobertoPrevato** [comment]
Thanks again! :)

**Comment by RobertoPrevato** [comment]
Writing for future record.

Now #BlackSheep is ASGI compatible. It drops completely its previous implementation of http server, so it requires an ASGI server to run. The HTTP client component is still present, mostly unchanged, and depends on httptools because it uses its response parser.

BlackSheep implements its own functions to write response bytes (using Cython).

For now I tested only with #uvicorn, but it should work with #daphne and #hypercorn, too. :cherries:

**Comment by tomchristie** [comment]
Nice one. 👍
