### ISSUE TITLE
Jinja2 has an async mode

### ISSUE THREAD

**Issue by pgjones** [RobertoPrevato/BlackSheep#9]
Unless I'm mistaken, you could make use of the [Jinja2 async mode](http://jinja.pocoo.org/docs/2.10/api/#async-support), (an example in [Quart](https://gitlab.com/pgjones/quart/blob/master/quart/templating.py#L13)).

**Comment by RobertoPrevato** [comment]
Thanks for the heads up. I read about async support in Jinja2 in the past, but I need to look more into this. So far I sticked to the sync api for this task, because I tend to think of HTML rendering like a CPU bound task (like building HTML, when the context is already at hand in memory), rather than network bound. I will make my hands dirtier on this subject - tomorrow I add a task to the **Development** project in GitHub.

**Comment by RobertoPrevato** [comment]
Hi @pgjones 
This has been added with https://github.com/RobertoPrevato/BlackSheep/commit/8dffcad47f3c735802aa535a3ee4b3e69801f944

Support for Jinja2 `enable_async` has been added, together with tests and improved code api to render views. :+1:

**Comment by pgjones** [comment]
🎉
